import type { WorldRuntimeBinding } from "../contracts";

/**
 * The Force & Motion package predates durable source snapshots. Its OpenStax
 * reference is retained as explicitly incomplete legacy metadata, rather than
 * being promoted to reviewed source authority by this runtime binding.
 */
export const FORCE_AND_MOTION_RUNTIME_BINDING = {
  protocolVersion: "1.1.0",
  semanticStages: [
    "encounter",
    "commit_model",
    "interpret_two_readings",
    "name_disagreement",
    "commit_test_prediction",
    "run_separating_experience",
    "governed_support",
    "reconstruct",
    "withdraw_instructional_ai",
    "cold_transfer",
    "bounded_result",
    "return_or_apply",
  ],
  actions: [
    { id: "action.force-and-motion.learner-operation", kind: "learner_operation", label: "Learner-authored force and motion operation" },
    { id: "action.force-and-motion.support.attention", kind: "instructional_support", label: "Authored force and motion attention support" },
    { id: "action.force-and-motion.support.representation", kind: "instructional_support", label: "Authored force and motion representation support" },
    { id: "action.force-and-motion.support.repair", kind: "instructional_support", label: "Authored force and motion repair support" },
    { id: "action.force-and-motion.interpretation.model", kind: "instructional_support", label: "Reviewed model interpretation support" },
    { id: "action.force-and-motion.interpretation.fallback.missing-key", kind: "instructional_support", label: "Authored missing-key interpretation fallback" },
    { id: "action.force-and-motion.interpretation.fallback.disabled", kind: "instructional_support", label: "Authored disabled interpretation fallback" },
    { id: "action.force-and-motion.interpretation.fallback.timeout", kind: "instructional_support", label: "Authored timeout interpretation fallback" },
    { id: "action.force-and-motion.interpretation.fallback.api-error", kind: "instructional_support", label: "Authored API-error interpretation fallback" },
    { id: "action.force-and-motion.interpretation.fallback.refusal", kind: "instructional_support", label: "Authored refusal interpretation fallback" },
    { id: "action.force-and-motion.interpretation.fallback.malformed-output", kind: "instructional_support", label: "Authored malformed-output interpretation fallback" },
    { id: "action.force-and-motion.interpretation.fallback.invalid-enum", kind: "instructional_support", label: "Authored invalid-enum interpretation fallback" },
    { id: "action.force-and-motion.interpretation.fallback.unsupported-evidence", kind: "instructional_support", label: "Authored unsupported-evidence interpretation fallback" },
    { id: "action.force-and-motion.interpretation.fallback.incompatible-probe", kind: "instructional_support", label: "Authored incompatible-probe interpretation fallback" },
    { id: "action.force-and-motion.interpretation.fallback.answer-leakage", kind: "instructional_support", label: "Authored answer-leakage interpretation fallback" },
    { id: "action.force-and-motion.interpretation.fallback.ambiguous-input", kind: "instructional_support", label: "Authored ambiguous-input interpretation fallback" },
    { id: "action.force-and-motion.model", kind: "model_action", label: "Bounded force and motion interpretation action" },
    { id: "action.force-and-motion.replay", kind: "experience_replay", label: "Separating-experience replay" },
    { id: "action.force-and-motion.access", kind: "access_accommodation", label: "Construct-preserving access accommodation" },
    { id: "action.force-and-motion.reset", kind: "reset", label: "Start a new force and motion investigation" },
  ],
  support: {
    policyId: "policy.force-and-motion.interpretation.v1",
    allowedDuringProof: false,
    recordsCognitiveSupport: true,
    catalog: [
      { actionId: "action.force-and-motion.support.attention", stage: "governed_support", source: "authored", tier: "attention", maxOccurrences: 1, answerExposing: false, policyId: "policy.force-and-motion.interpretation.v1", providerId: null, modelIdentity: { mode: "not_applicable" }, fallbackReason: null },
      { actionId: "action.force-and-motion.support.representation", stage: "governed_support", source: "authored", tier: "representation", maxOccurrences: 1, answerExposing: false, policyId: "policy.force-and-motion.interpretation.v1", providerId: null, modelIdentity: { mode: "not_applicable" }, fallbackReason: null },
      { actionId: "action.force-and-motion.support.repair", stage: "governed_support", source: "authored", tier: "repair", maxOccurrences: 1, answerExposing: false, policyId: "policy.force-and-motion.interpretation.v1", providerId: null, modelIdentity: { mode: "not_applicable" }, fallbackReason: null },
      { actionId: "action.force-and-motion.interpretation.model", stage: "interpret_two_readings", source: "model", tier: "representation", maxOccurrences: 1, answerExposing: false, policyId: "policy.force-and-motion.interpretation.v1", providerId: "openai", modelIdentity: { mode: "runtime_selected" }, fallbackReason: null },
      { actionId: "action.force-and-motion.interpretation.fallback.missing-key", stage: "interpret_two_readings", source: "authored", tier: "representation", maxOccurrences: 1, answerExposing: false, policyId: "policy.force-and-motion.interpretation.v1", providerId: null, modelIdentity: { mode: "not_applicable" }, fallbackReason: "missing_key" },
      { actionId: "action.force-and-motion.interpretation.fallback.disabled", stage: "interpret_two_readings", source: "authored", tier: "representation", maxOccurrences: 1, answerExposing: false, policyId: "policy.force-and-motion.interpretation.v1", providerId: null, modelIdentity: { mode: "not_applicable" }, fallbackReason: "disabled" },
      { actionId: "action.force-and-motion.interpretation.fallback.timeout", stage: "interpret_two_readings", source: "authored", tier: "representation", maxOccurrences: 1, answerExposing: false, policyId: "policy.force-and-motion.interpretation.v1", providerId: null, modelIdentity: { mode: "not_applicable" }, fallbackReason: "timeout" },
      { actionId: "action.force-and-motion.interpretation.fallback.api-error", stage: "interpret_two_readings", source: "authored", tier: "representation", maxOccurrences: 1, answerExposing: false, policyId: "policy.force-and-motion.interpretation.v1", providerId: null, modelIdentity: { mode: "not_applicable" }, fallbackReason: "api_error" },
      { actionId: "action.force-and-motion.interpretation.fallback.refusal", stage: "interpret_two_readings", source: "authored", tier: "representation", maxOccurrences: 1, answerExposing: false, policyId: "policy.force-and-motion.interpretation.v1", providerId: null, modelIdentity: { mode: "not_applicable" }, fallbackReason: "refusal" },
      { actionId: "action.force-and-motion.interpretation.fallback.malformed-output", stage: "interpret_two_readings", source: "authored", tier: "representation", maxOccurrences: 1, answerExposing: false, policyId: "policy.force-and-motion.interpretation.v1", providerId: null, modelIdentity: { mode: "not_applicable" }, fallbackReason: "malformed_output" },
      { actionId: "action.force-and-motion.interpretation.fallback.invalid-enum", stage: "interpret_two_readings", source: "authored", tier: "representation", maxOccurrences: 1, answerExposing: false, policyId: "policy.force-and-motion.interpretation.v1", providerId: null, modelIdentity: { mode: "not_applicable" }, fallbackReason: "invalid_enum" },
      { actionId: "action.force-and-motion.interpretation.fallback.unsupported-evidence", stage: "interpret_two_readings", source: "authored", tier: "representation", maxOccurrences: 1, answerExposing: false, policyId: "policy.force-and-motion.interpretation.v1", providerId: null, modelIdentity: { mode: "not_applicable" }, fallbackReason: "unsupported_evidence" },
      { actionId: "action.force-and-motion.interpretation.fallback.incompatible-probe", stage: "interpret_two_readings", source: "authored", tier: "representation", maxOccurrences: 1, answerExposing: false, policyId: "policy.force-and-motion.interpretation.v1", providerId: null, modelIdentity: { mode: "not_applicable" }, fallbackReason: "incompatible_probe" },
      { actionId: "action.force-and-motion.interpretation.fallback.answer-leakage", stage: "interpret_two_readings", source: "authored", tier: "representation", maxOccurrences: 1, answerExposing: false, policyId: "policy.force-and-motion.interpretation.v1", providerId: null, modelIdentity: { mode: "not_applicable" }, fallbackReason: "answer_leakage" },
      { actionId: "action.force-and-motion.interpretation.fallback.ambiguous-input", stage: "interpret_two_readings", source: "authored", tier: "representation", maxOccurrences: 1, answerExposing: false, policyId: "policy.force-and-motion.interpretation.v1", providerId: null, modelIdentity: { mode: "not_applicable" }, fallbackReason: "ambiguous_input" },
    ],
  },
  proof: {
    proofClaimId: "proof.force-motion.independent-transfer",
    validatorId: "validator.force-motion-transfer.v1",
    taskCode: "cargo_pod_force_graph",
    taskFamilyId: "task-family.force-motion.cargo-pod-cold-transfer.v1",
    blockedActionKinds: ["instructional_support", "model_action", "experience_replay"],
    accessAllowed: true,
  },
  evidence: {
    receiptSchemaVersion: "1.1.0",
    proofAuthority: "honour_based",
    persistence: "not_persisted",
  },
  returnProof: {
    enabled: false,
    policyId: "policy.force-and-motion.return-proof.unavailable.v1",
  },
  access: {
    accommodations: [
      {
        id: "access.force-and-motion.text-alternative",
        kind: "text_alternative",
        modality: "textual",
        representation: "text_description",
        constructPreservation: "preserves_construct",
        answerChanging: false,
        policyVersion: "1.0.0",
        nonvisualAlternative: true,
      },
      {
        id: "access.force-and-motion.keyboard-operation",
        kind: "keyboard_operation",
        modality: "keyboard",
        representation: "native_control",
        constructPreservation: "preserves_construct",
        answerChanging: false,
        policyVersion: "1.0.0",
        nonvisualAlternative: false,
      },
      {
        id: "access.force-and-motion.reduced-motion",
        kind: "motion_reduction",
        modality: "motion",
        representation: "reduced_motion",
        constructPreservation: "preserves_construct",
        answerChanging: false,
        policyVersion: "1.0.0",
        nonvisualAlternative: false,
      },
    ],
    focusTargetId: "focus.force-and-motion.stage-main",
    reducedMotionPolicyId: "motion.force-and-motion.reduce-stage-transition",
  },
  sourceBindings: [
    {
      domainSourceRef: "source.openstax.newtons-first-law",
      sourceItemId: "source.openstax.newtons-first-law",
      sourcePackageId: null,
      sourcePackageVersion: null,
      sourceSnapshotDigest: null,
      locatorIds: [],
      claimIds: [],
      rightsRecordId: null,
      reviewDecisionIds: [],
      provenanceStatus: "legacy_metadata_only",
    },
  ],
} as const satisfies WorldRuntimeBinding;
