import SwiftUI

struct ActionBriefView: View {
    var body: some View {
        ForgePage(screenID: "IOS-07") {
            ForgeScreenHeader(
                "Action brief",
                title: "Compare support and contradiction.",
                detail: "Use the reviewed source pair. Keep one condition visible."
            )

            ForgeCard {
                LabeledContent("Operation", value: "Compare")
                LabeledContent("Expected effort", value: "12-15 minutes")
                LabeledContent("Assistance", value: "Available after a useful attempt")
                LabeledContent("Evidence", value: "No record before submission")
            }

            NavigationLink(value: ForgeRoute.attempt) {
                Text("Start attempt")
            }
            .buttonStyle(ForgePrimaryButtonStyle())
        }
        .navigationTitle("Action brief")
        .navigationBarTitleDisplayMode(.inline)
    }
}

struct AttemptView: View {
    @State private var response = ""

    var body: some View {
        ForgePage(screenID: "IOS-08") {
            ForgeScreenHeader(
                "Your operation",
                title: "What does this source establish?",
                detail: "Use the excerpt. Do not restate it as a universal conclusion."
            )

            ForgeCard {
                ForgeStatus(label: "Reviewed source", color: .forgeAI)
                Text("The reported result applies to the tested population and conditions.")
                    .font(.body)
            }

            TextField("Explain the result and its condition.", text: $response, axis: .vertical)
                .lineLimit(6...12)
                .padding(ForgeSpacing.standard)
                .background(.background.secondary, in: RoundedRectangle(cornerRadius: 12))
                .accessibilityLabel("Learner attempt")

            NavigationLink(value: ForgeRoute.repair) {
                Text("Commit attempt")
            }
            .buttonStyle(ForgePrimaryButtonStyle())
        }
        .navigationTitle("Attempt")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar(.hidden, for: .tabBar)
    }
}

struct RepairView: View {
    var body: some View {
        ForgePage(screenID: "IOS-09") {
            ForgeScreenHeader(
                "Repair",
                title: "Your claim reaches beyond the tested population.",
                detail: "This scaffold was generated by AI and reviewed for this sample."
            )

            ForgeCard {
                ForgeStatus(label: "Smallest useful scaffold", color: .forgeAI)
                Text("Compare these two statements.")
                    .font(.headline)
                Text("The tested group showed the result.")
                Text("All learners will show the result.")
                Text("Name the unsupported change in scope.")
                    .font(.subheadline.weight(.semibold))
                    .foregroundStyle(Color.forgeAI)
            }

            NavigationLink(value: ForgeRoute.protectedProof) {
                Text("Revise my answer")
            }
            .buttonStyle(ForgePrimaryButtonStyle())
        }
        .navigationTitle("Repair")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar(.hidden, for: .tabBar)
    }
}

struct ProtectedProofView: View {
    @State private var response = ""

    var body: some View {
        ForgePage(screenID: "IOS-10") {
            ForgeScreenHeader(
                "Protected proof",
                title: "Separate the claim, source, and inference.",
                detail: "No instructional help is available during this proof."
            )

            ForgeCard {
                ForgeStatus(label: "Fresh case", color: .forgeOrange)
                Text("One source reports a result. A second source tests a different condition.")
                    .font(.headline)
            }

            TextField("Write your independent response.", text: $response, axis: .vertical)
                .lineLimit(6...12)
                .padding(ForgeSpacing.standard)
                .background(.background.secondary, in: RoundedRectangle(cornerRadius: 12))

            Button("Submit proof") {}
                .buttonStyle(ForgePrimaryButtonStyle())
        }
        .navigationTitle("Proof")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar(.hidden, for: .tabBar)
    }
}

struct ReturnQueueView: View {
    var body: some View {
        ForgePage(screenID: "IOS-13") {
            ForgeScreenHeader(
                "Proof after delay",
                title: "Return to the capability, not the lesson.",
                detail: "Each return uses a fresh case and keeps prior help unavailable."
            )

            NavigationLink(value: ForgeRoute.protectedReturn) {
                ForgeCard {
                    ForgeStatus(label: "Due tomorrow", color: .forgeOrange)
                    Text("Claim and source")
                        .font(.headline)
                    Text("About 8 minutes. Fresh case.")
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                }
            }
            .buttonStyle(.plain)

            ForEach(["Support and contradiction", "Force model"], id: \.self) { title in
                ForgeCard {
                    Text(title).font(.headline)
                    Text("Ready later").font(.subheadline).foregroundStyle(.secondary)
                }
            }
        }
        .navigationTitle("Returns")
        .navigationBarTitleDisplayMode(.inline)
    }
}

struct ProtectedReturnView: View {
    var body: some View {
        ForgePage(screenID: "IOS-14") {
            ForgeScreenHeader(
                "Fresh case",
                title: "Can you use the distinction without the lesson?",
                detail: "No instructional help. Accessibility support remains available."
            )

            ForgeCard {
                LabeledContent("Window", value: "Open for one day")
                LabeledContent("Expected effort", value: "About 8 minutes")
                LabeledContent("Result", value: "One bounded record")
            }

            Button("Start protected return") {}
                .buttonStyle(ForgePrimaryButtonStyle())
        }
        .navigationTitle("Protected return")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar(.hidden, for: .tabBar)
    }
}
