import SwiftUI

struct ActionBriefView: View {
    var body: some View {
        ForgePage(screenID: "IOS-07") {
            ForgeScreenHeader(
                "Action brief",
                title: "Compare support and contradiction.",
                detail: "Use the reviewed source pair. Keep one condition visible."
            )

            ForgeCard {
                LabeledContent("Operation", value: "Compare")
                LabeledContent("Expected effort", value: "12-15 minutes")
                LabeledContent("Assistance", value: "Available after a useful attempt")
                LabeledContent("Evidence", value: "No record before submission")
            }

            NavigationLink(value: ForgeRoute.attempt(id: "support-contradiction")) {
                Text("Start attempt")
            }
            .buttonStyle(ForgePrimaryButtonStyle())
            .accessibilityIdentifier("ios.IOS-07.primary")
        }
        .navigationTitle("Action brief")
        .navigationBarTitleDisplayMode(.inline)
    }
}

struct AttemptView: View {
    @State private var response = ""
    @State private var operationState = ForgeOperationState.ready

    var body: some View {
        ForgePage(screenID: "IOS-08") {
            ForgeScreenHeader(
                "Your operation",
                title: "What does this source establish?",
                detail: "Use the excerpt. Do not restate it as a universal conclusion."
            )

            ForgeCard {
                ForgeStatus(label: "Reviewed source", color: ForgeTerrainColor.aiContribution)
                Text("The reported result applies to the tested population and conditions.")
                    .font(.body)
            }

            TextField("Explain the result and its condition.", text: $response, axis: .vertical)
                .lineLimit(nil)
                .padding(ForgeSpacing.standard)
                .background(ForgeTerrainColor.surface, in: RoundedRectangle(cornerRadius: 12))
                .accessibilityLabel("Learner attempt")

            ForgeOperationStatus(state: operationState)

            if case .failed = operationState {
                Button("Try again") {
                    operationState = .ready
                }
                .accessibilityIdentifier("ios.IOS-08.secondary")
            }

            Button(operationState == .saved ? "Attempt saved" : "Commit attempt") {
                commitAttempt()
            }
            .buttonStyle(ForgePrimaryButtonStyle())
            .accessibilityIdentifier("ios.IOS-08.primary")
            .disabled(operationState == .saving || operationState == .saved)

            if operationState == .saved {
                NavigationLink(value: ForgeRoute.repair(id: "support-contradiction")) {
                    Text("Continue to repair")
                }
                .accessibilityIdentifier("ios.IOS-08.secondary")
            }
        }
        .navigationTitle("Attempt")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar(.hidden, for: .tabBar)
    }

    private func commitAttempt() {
        guard !response.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            operationState = .failed("Write an attempt before committing.")
            return
        }
        operationState = .saved
    }
}

struct RepairView: View {
    var body: some View {
        ForgePage(screenID: "IOS-09") {
            ForgeScreenHeader(
                "Repair",
                title: "Your claim reaches beyond the tested population.",
                detail: "This scaffold was generated by AI and reviewed for this sample."
            )

            ForgeCard {
                ForgeStatus(label: "Smallest useful scaffold", color: ForgeTerrainColor.aiContribution)
                Text("Compare these two statements.")
                    .font(.headline)
                Text("The tested group showed the result.")
                Text("All learners will show the result.")
                Text("Name the unsupported change in scope.")
                    .font(.subheadline.weight(.semibold))
                    .foregroundStyle(ForgeTerrainColor.aiContribution)
            }

            NavigationLink(value: ForgeRoute.proof(id: "support-contradiction")) {
                Text("Revise my answer")
            }
            .buttonStyle(ForgePrimaryButtonStyle())
            .accessibilityIdentifier("ios.IOS-09.primary")
        }
        .navigationTitle("Repair")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar(.hidden, for: .tabBar)
    }
}

struct ProtectedProofView: View {
    @State private var response = ""
    @State private var operationState = ForgeOperationState.ready

    var body: some View {
        ForgePage(screenID: "IOS-10") {
            ForgeScreenHeader(
                "Protected proof",
                title: "Separate the claim, source, and inference.",
                detail: "No instructional help is available during this proof."
            )

            ForgeCard {
                ForgeStatus(label: "Fresh case", color: ForgeTerrainColor.learnerAction)
                Text("One source reports a result. A second source tests a different condition.")
                    .font(.headline)
            }

            TextField("Write your independent response.", text: $response, axis: .vertical)
                .lineLimit(nil)
                .padding(ForgeSpacing.standard)
                .background(ForgeTerrainColor.surface, in: RoundedRectangle(cornerRadius: 12))
                .accessibilityLabel("Independent proof response")

            ForgeOperationStatus(state: operationState)

            if case .failed = operationState {
                Button("Try again") {
                    operationState = .ready
                }
                .accessibilityIdentifier("ios.IOS-10.secondary")
            }

            Button(operationState == .submitted ? "Proof submitted" : "Submit proof") {
                submitProof()
            }
                .buttonStyle(ForgePrimaryButtonStyle())
                .accessibilityIdentifier("ios.IOS-10.primary")
                .disabled(operationState == .saving || operationState == .submitted)

            if operationState == .submitted {
                Text("Saved locally. This reference does not create canonical evidence.")
                    .font(.footnote)
                    .foregroundStyle(ForgeTerrainColor.textMuted)
            }
        }
        .navigationTitle("Proof")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar(.hidden, for: .tabBar)
    }

    private func submitProof() {
        guard !response.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            operationState = .failed("Write an independent response before submitting.")
            return
        }
        operationState = .submitted
    }
}

struct ReturnQueueView: View {
    var body: some View {
        ForgePage(screenID: "IOS-13") {
            ForgeScreenHeader(
                "Proof after delay",
                title: "Return to the capability, not the lesson.",
                detail: "Each return uses a fresh case and keeps prior help unavailable."
            )

            NavigationLink(value: ForgeRoute.protectedReturn(id: "claim-source")) {
                ForgeCard {
                    ForgeStatus(label: "Due tomorrow", color: ForgeTerrainColor.learnerAction)
                    Text("Claim and source")
                        .font(.headline)
                    Text("About 8 minutes. Fresh case.")
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                }
            }
            .buttonStyle(.plain)

            ForEach(["Support and contradiction", "Force model"], id: \.self) { title in
                ForgeCard {
                    Text(title).font(.headline)
                    Text("Ready later").font(.subheadline).foregroundStyle(.secondary)
                }
            }
        }
        .navigationTitle("Returns")
        .navigationBarTitleDisplayMode(.inline)
    }
}

struct ProtectedReturnView: View {
    @State private var operationState = ForgeOperationState.ready

    var body: some View {
        ForgePage(screenID: "IOS-14") {
            ForgeScreenHeader(
                "Fresh case",
                title: "Can you use the distinction without the lesson?",
                detail: "No instructional help. Accessibility support remains available."
            )

            ForgeCard {
                LabeledContent("Window", value: "Open for one day")
                LabeledContent("Expected effort", value: "About 8 minutes")
                LabeledContent("Result", value: "One bounded record")
            }

            ForgeOperationStatus(state: operationState)

            Button(operationState == .saved ? "Protected return ready" : "Start protected return") {
                operationState = .saved
            }
                .buttonStyle(ForgePrimaryButtonStyle())
                .accessibilityIdentifier("ios.IOS-14.primary")
                .disabled(operationState == .saved)
        }
        .navigationTitle("Protected return")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar(.hidden, for: .tabBar)
    }
}
