import type { ProbeDefinition, ProbeId } from "@/src/types/modelshift";

export const PROBES: Record<ProbeId, ProbeDefinition> = {
  friction_contrast: {
    id: "friction_contrast",
    title: "Friction or no friction?",
    shortTitle: "Friction contrast",
    purpose: "Separate force-free coasting from slowing caused by resistance.",
    connection: "The two tracks differ in only one way: after the push, friction acts on one puck and no horizontal force acts on the other.",
    compatibleHypotheses: ["continuous_force_required", "implicit_resistance", "mixed_or_unclear"],
    defaultQuestionId: "what_differs_between_cases",
    predictionPrompt: "At six seconds, which puck will still be moving faster?",
    predictionChoices: [
      { id: "no_resistance_faster", label: "The no-resistance puck", description: "It receives no horizontal force after the push." },
      { id: "same_speed", label: "They will have the same speed", description: "The same initial push decides everything." },
    ],
    correctPredictionId: "no_resistance_faster",
    adjustableControl: "friction",
  },
  brief_vs_continuous_force: {
    id: "brief_vs_continuous_force",
    title: "Brief push or continuous push?",
    shortTitle: "Push duration",
    purpose: "Separate a force that changes velocity from a force that merely sustains it.",
    connection: "Both objects start together; one stops receiving force after one second while the other keeps accelerating.",
    compatibleHypotheses: ["continuous_force_required", "force_equals_velocity", "scientific_or_near_scientific"],
    defaultQuestionId: "compare_force_and_velocity_graphs",
    predictionPrompt: "When the brief push ends, what happens to that puck's velocity?",
    predictionChoices: [
      { id: "brief_velocity_constant", label: "It stays constant", description: "The velocity stops changing when net force becomes zero." },
      { id: "brief_velocity_falls", label: "It falls toward zero", description: "Without a push, the existing motion fades." },
    ],
    correctPredictionId: "brief_velocity_constant",
    adjustableControl: "force_duration",
  },
  zero_force_velocity_contrast: {
    id: "zero_force_velocity_contrast",
    title: "Same force, different starting motion",
    shortTitle: "Zero-force contrast",
    purpose: "Show that zero net force preserves the velocity an object already has.",
    connection: "Both objects have zero net force; one begins at rest and one already has velocity.",
    compatibleHypotheses: ["force_equals_velocity", "scientific_or_near_scientific"],
    defaultQuestionId: "which_quantity_changed",
    predictionPrompt: "With zero net force on both, what happens next?",
    predictionChoices: [
      { id: "keep_starting_velocity", label: "Each keeps its starting velocity", description: "Rest stays rest; motion stays constant motion." },
      { id: "both_become_still", label: "Both become still", description: "Zero force means zero velocity." },
    ],
    correctPredictionId: "keep_starting_velocity",
    adjustableControl: "none",
  },
  neutral_core_probe: {
    id: "neutral_core_probe",
    title: "The baseline coast test",
    shortTitle: "Baseline test",
    purpose: "Directly compare force-free motion with frictional slowing without assuming one interpretation.",
    connection: "Because more than one explanation fits, the baseline test changes only the force after the push.",
    compatibleHypotheses: [
      "continuous_force_required",
      "implicit_resistance",
      "force_equals_velocity",
      "scientific_or_near_scientific",
      "mixed_or_unclear",
    ],
    defaultQuestionId: "neutral_observation_prompt",
    predictionPrompt: "Which track should show a changing velocity after the push?",
    predictionChoices: [
      { id: "friction_changes_velocity", label: "Only the friction track", description: "A force still acts there after the push." },
      { id: "both_change_velocity", label: "Both tracks", description: "Motion changes whenever the push stops." },
    ],
    correctPredictionId: "friction_changes_velocity",
    adjustableControl: "friction",
  },
};
